services:
  api:
    container_name: Payroll-worker-dev
    image: payroll-worker-dev
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      platforms:
        - linux/amd64
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:debug
    ports:
      - 3001:3001
      - 9229:9229
    networks:
      - payrollback_network
networks:
  payrollback_network:
    external: true
