name: Deploy to Azure Container App (STAGE)

on:
  push:
    branches:
      - staging # Only runs on merge/push to stage
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: animorhpayrolldev.azurecr.io
  ACR_NAME: animorhpayrolldev
  CONTAINER_APP_NAME: ca-dev-payroll-worker
  RESOURCE_GROUP: rg-payroll-dev
  IMAGE_NAME: payroll-worker-stg
  NODE_ENV: staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEPLOY }}

      - name: Log in to Azure Container Registry
        run: az acr login --name $ACR_NAME

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.run_number }}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build \
            --build-arg NODE_ENV=$NODE_ENV \
            -t $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG \
            -f Dockerfile .

      - name: Push image to ACR
        run: docker push $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:${{ env.IMAGE_TAG }}

      - name: Deploy to Azure Container App (STAGE)
        run: |
          az containerapp update \
            --name $CONTAINER_APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --image $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:${{ env.IMAGE_TAG }}

      - name: Output deployed version
        run: echo "✅ Deployed staging version $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:${{ env.IMAGE_TAG }}"
